# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maj_edge <- function(trees) {
    .Call('_MMCTime_maj_edge', PACKAGE = 'MMCTime', trees)
}

nodes_in_clades <- function(trees, clades) {
    .Call('_MMCTime_nodes_in_clades', PACKAGE = 'MMCTime', trees, clades)
}

find_clade_indices <- function(trees, clades) {
    .Call('_MMCTime_find_clade_indices', PACKAGE = 'MMCTime', trees, clades)
}

#' @export
median_clade_times <- function(x, all_trees, ts) {
    invisible(.Call('_MMCTime_median_clade_times', PACKAGE = 'MMCTime', x, all_trees, ts))
}

sim_km_beta <- function(samp_times, n_samp, phi, nu, alpha) {
    .Call('_MMCTime_sim_km_beta', PACKAGE = 'MMCTime', samp_times, n_samp, phi, nu, alpha)
}

sim_beta <- function(samp_times, n_samp, nu, alpha) {
    .Call('_MMCTime_sim_beta', PACKAGE = 'MMCTime', samp_times, n_samp, nu, alpha)
}

sim_kingman <- function(samp_times, n_samp, nu) {
    .Call('_MMCTime_sim_kingman', PACKAGE = 'MMCTime', samp_times, n_samp, nu)
}

sim_ds <- function(samp_times, n_samp, phi, nu) {
    .Call('_MMCTime_sim_ds', PACKAGE = 'MMCTime', samp_times, n_samp, phi, nu)
}

initialise_times <- function(phydata, mod_state, branch_data, mu) {
    invisible(.Call('_MMCTime_initialise_times', PACKAGE = 'MMCTime', phydata, mod_state, branch_data, mu))
}

duplicate_mc_state <- function(mod_state) {
    .Call('_MMCTime_duplicate_mc_state', PACKAGE = 'MMCTime', mod_state)
}

mc_state_copy_to <- function(src, dest) {
    invisible(.Call('_MMCTime_mc_state_copy_to', PACKAGE = 'MMCTime', src, dest))
}

duplicate_par_state <- function(mod_state) {
    .Call('_MMCTime_duplicate_par_state', PACKAGE = 'MMCTime', mod_state)
}

par_state_copy_to <- function(src, dest) {
    invisible(.Call('_MMCTime_par_state_copy_to', PACKAGE = 'MMCTime', src, dest))
}

duplicate_tree <- function(phydata) {
    .Call('_MMCTime_duplicate_tree', PACKAGE = 'MMCTime', phydata)
}

tree_copy_to <- function(src, dest) {
    invisible(.Call('_MMCTime_tree_copy_to', PACKAGE = 'MMCTime', src, dest))
}

times_from_taus <- function(phydata, mod_state) {
    invisible(.Call('_MMCTime_times_from_taus', PACKAGE = 'MMCTime', phydata, mod_state))
}

#' @export
taus_from_times <- function(phydata, mod_state) {
    invisible(.Call('_MMCTime_taus_from_times', PACKAGE = 'MMCTime', phydata, mod_state))
}

validate_times <- function(phydata, mod_state) {
    .Call('_MMCTime_validate_times', PACKAGE = 'MMCTime', phydata, mod_state)
}

build_topo_mat <- function(br_mat, n_node, root_pos, cutoff) {
    .Call('_MMCTime_build_topo_mat', PACKAGE = 'MMCTime', br_mat, n_node, root_pos, cutoff)
}

build_branch_data <- function(br_mat, n_node, root_pos) {
    .Call('_MMCTime_build_branch_data', PACKAGE = 'MMCTime', br_mat, n_node, root_pos)
}

find_sbounds <- function(br_mat, tip_times, n_tip, root_idx) {
    .Call('_MMCTime_find_sbounds', PACKAGE = 'MMCTime', br_mat, tip_times, n_tip, root_idx)
}

#' @export
binary_to_mm <- function(phydata, mod_state, tol = 1e-8) {
    invisible(.Call('_MMCTime_binary_to_mm', PACKAGE = 'MMCTime', phydata, mod_state, tol))
}

find_pivots <- function(phydata, branch_data) {
    .Call('_MMCTime_find_pivots', PACKAGE = 'MMCTime', phydata, branch_data)
}

as_lambda_events <- function(phydata, mod_state) {
    .Call('_MMCTime_as_lambda_events', PACKAGE = 'MMCTime', phydata, mod_state)
}

rwm_tau_move <- function(phydata, curr_mc_state, prop_mc_state, sd) {
    .Call('_MMCTime_rwm_tau_move', PACKAGE = 'MMCTime', phydata, curr_mc_state, prop_mc_state, sd)
}

rwm_par_move <- function(curr_par_state, prop_par_state, sd) {
    .Call('_MMCTime_rwm_par_move', PACKAGE = 'MMCTime', curr_par_state, prop_par_state, sd)
}

push_mm_move <- function(phydata, curr_state, prop_state, sd, branch_data) {
    .Call('_MMCTime_push_mm_move', PACKAGE = 'MMCTime', phydata, curr_state, prop_state, sd, branch_data)
}

topo_move <- function(curr_phydata, curr_state, prop_phydata, prop_state, branch_data, pivots) {
    .Call('_MMCTime_topo_move', PACKAGE = 'MMCTime', curr_phydata, curr_state, prop_phydata, prop_state, branch_data, pivots)
}

root_move <- function(curr_phydata, curr_state, prop_phydata, prop_state) {
    .Call('_MMCTime_root_move', PACKAGE = 'MMCTime', curr_phydata, curr_state, prop_phydata, prop_state)
}

transform_kmb_arc <- function(par_state) {
    .Call('_MMCTime_transform_kmb_arc', PACKAGE = 'MMCTime', par_state)
}

prob_kmb_arc <- function(phydata, mod_state, par_state, branch_data) {
    .Call('_MMCTime_prob_kmb_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state, branch_data)
}

coal_lp_kmb_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_coal_lp_kmb_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

summaries_kmb_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_summaries_kmb_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

transform_ds_arc <- function(par_state) {
    .Call('_MMCTime_transform_ds_arc', PACKAGE = 'MMCTime', par_state)
}

prob_ds_arc <- function(phydata, mod_state, par_state, branch_data) {
    .Call('_MMCTime_prob_ds_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state, branch_data)
}

coal_lp_ds_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_coal_lp_ds_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

summaries_ds_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_summaries_ds_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

transform_beta_arc <- function(par_state) {
    .Call('_MMCTime_transform_beta_arc', PACKAGE = 'MMCTime', par_state)
}

prob_beta_arc <- function(phydata, mod_state, par_state, branch_data) {
    .Call('_MMCTime_prob_beta_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state, branch_data)
}

coal_lp_beta_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_coal_lp_beta_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

summaries_beta_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_summaries_beta_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

transform_km_arc <- function(par_state) {
    .Call('_MMCTime_transform_km_arc', PACKAGE = 'MMCTime', par_state)
}

prob_km_arc <- function(phydata, mod_state, par_state, branch_data) {
    .Call('_MMCTime_prob_km_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state, branch_data)
}

coal_lp_km_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_coal_lp_km_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

summaries_km_arc <- function(phydata, mod_state, par_state) {
    .Call('_MMCTime_summaries_km_arc', PACKAGE = 'MMCTime', phydata, mod_state, par_state)
}

taus_to_times_logJ <- function(phydata, mod_state) {
    .Call('_MMCTime_taus_to_times_logJ', PACKAGE = 'MMCTime', phydata, mod_state)
}

times_to_taus_logJ <- function(phydata, mod_state) {
    .Call('_MMCTime_times_to_taus_logJ', PACKAGE = 'MMCTime', phydata, mod_state)
}

kingman_lp <- function(phydata, mod_state, nu) {
    .Call('_MMCTime_kingman_lp', PACKAGE = 'MMCTime', phydata, mod_state, nu)
}

km_beta_lp <- function(phydata, mod_state, nu, phi, alpha) {
    .Call('_MMCTime_km_beta_lp', PACKAGE = 'MMCTime', phydata, mod_state, nu, phi, alpha)
}

ds_lp <- function(phydata, mod_state, nu, phi) {
    .Call('_MMCTime_ds_lp', PACKAGE = 'MMCTime', phydata, mod_state, nu, phi)
}

beta_lp <- function(phydata, mod_state, nu, alpha) {
    .Call('_MMCTime_beta_lp', PACKAGE = 'MMCTime', phydata, mod_state, nu, alpha)
}

